
server:
  port: 8082

spring:
  application:
    name: go-back-home-service

  datasource:
    url: jdbc:postgresql://localhost:5432/go_home
    username: bulldozer
    password: bulldozer
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    username: bulldozer
    password: bulldozer
    virtual-host: bulldozer
    # Streams does not support requeue on rejected messages.
    listener:
      simple:
        default-requeue-rejected: false
      direct:
        default-requeue-rejected: false

  security:
    oauth2:
      authorizationserver:
        client:
          inventory-client:
            registration:
              client-id: "go-home-client"
              client-secret: "{noop}my-client-secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
                - "password"
              redirect-uris:
                - "http://127.0.0.1:${server.port}/login/oauth2/code/go-home-client"
              scopes:
                - "openid"

      resourceserver:
        jwt:
          issuer-uri: http://localhost:${server.port}/oauth2/authserver.

bulldozer:
  messaging:
    listener:
      enabled: true
  go-home:
    notification-trigger-time: "13:39"
    last-consumption-period: PT6H

