server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: bulldozer
    password: bulldozer
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    username: bulldozer
    password: bulldozer
    virtual-host: bulldozer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090

bulldozer:
  messaging:
    listener:
      enabled: true
  inventory:
    # How many remaining beers to trigger low stock event
    low-stock-trigger: 5