server:
  port: 8090

spring:
  application:
    name: igloo-auth-server

  security:
    oauth2:
      authorizationserver:
        client:
          igloo-client:
            registration:
              client-id: "igloo-client"
              client-secret: "{noop}my-client-secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8000/login/oauth2/code/igloo-client"
              scopes:
                - "openid"
                - "profile"
            require-proof-key: false
            require-authorization-consent: false